---
- src: git@github.com:Vndr3w/vector-role.git
  scm: git
  version: "1.0.0"
  name: vector-role

- src: git@github.com:Vndr3w/lighthouse-role.git
  scm: git
  version: "1.0.0"
  name: lighthouse-role

- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse
